import type { District, Food, Restaurant } from "./food-types"

export const districts: District[] = [
  {
    id: 1,
    name: "1",
    slug: "quan-1",
    description: "Trung tâm thành phố với nhiều địa điểm ăn uống nổi tiếng",
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 2,
    name: "2",
    slug: "quan-2",
    description: "Khu vực hiện đại với nhiều nhà hàng sang trọng",
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 3,
    name: "3",
    slug: "quan-3",
    description: "Nổi tiếng với phố ẩm thực đa dạng",
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 4,
    name: "4",
    slug: "quan-4",
    description: "Khu vực ven sông với nhiều quán hải sản",
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 5,
    name: "5",
    slug: "quan-5",
    description: "Khu Chợ Lớn với ẩm thực Hoa đặc sắc",
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 6,
    name: "6",
    slug: "quan-6",
    description: "Nhiều quán ăn bình dân ngon và rẻ",
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 7,
    name: "7",
    slug: "quan-7",
    description: "Khu đô thị Phú Mỹ Hưng với nhiều nhà hàng quốc tế",
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 8,
    name: "8",
    slug: "quan-8",
    description: "Nhiều quán ăn đường phố đặc sắc",
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 9,
    name: "9",
    slug: "quan-9",
    description: "Khu vực mới phát triển với nhiều quán ăn hiện đại",
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 10,
    name: "10",
    slug: "quan-10",
    description: "Nổi tiếng với khu ẩm thực đường phố",
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 11,
    name: "11",
    slug: "quan-11",
    description: "Nhiều quán ăn truyền thống lâu đời",
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 12,
    name: "12",
    slug: "quan-12",
    description: "Khu vực ngoại ô với ẩm thực đa dạng",
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 13,
    name: "Bình Thạnh",
    slug: "quan-binh-thanh",
    description: "Nhiều quán cà phê và quán ăn độc đáo",
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 14,
    name: "Phú Nhuận",
    slug: "quan-phu-nhuan",
    description: "Khu vực sầm uất với nhiều quán ăn ngon",
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 15,
    name: "Tân Bình",
    slug: "quan-tan-binh",
    description: "Gần sân bay với nhiều quán ăn đa dạng",
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 16,
    name: "Tân Phú",
    slug: "quan-tan-phu",
    description: "Nhiều quán ăn bình dân và trung cấp",
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 17,
    name: "Gò Vấp",
    slug: "quan-go-vap",
    description: "Khu vực đông dân cư với nhiều quán ăn đa dạng",
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 18,
    name: "Thủ Đức",
    slug: "thanh-pho-thu-duc",
    description: "Thành phố mới với nhiều khu ẩm thực hiện đại",
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
]

export const foods: Food[] = [
  // Món Ăn
  {
    id: 1,
    name: "Cơm Tấm",
    slug: "com-tam",
    description: "Món cơm tấm Sài Gòn nổi tiếng với sườn nướng, bì, chả, trứng và nước mắm ngọt đặc trưng",
    category: "Món Ăn",
    districts: [
      "quan-1",
      "quan-3",
      "quan-5",
      "quan-10",
      "quan-binh-thanh",
      "quan-phu-nhuan",
      "quan-go-vap",
      "quan-tan-binh",
    ],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 2,
    name: "Phở",
    slug: "pho",
    description: "Món phở truyền thống với nước dùng ngọt thanh, bánh phở mềm và thịt bò tái hoặc chín",
    category: "Món Ăn",
    districts: [
      "quan-1",
      "quan-3",
      "quan-5",
      "quan-phu-nhuan",
      "quan-binh-thanh",
      "quan-go-vap",
      "quan-tan-binh",
      "quan-7",
    ],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 3,
    name: "Bánh Mì",
    slug: "banh-mi",
    description: "Bánh mì giòn với nhân đa dạng như thịt, chả, pate, rau và sốt đặc biệt",
    category: "Món Ăn",
    districts: [
      "quan-1",
      "quan-3",
      "quan-4",
      "quan-10",
      "quan-binh-thanh",
      "quan-go-vap",
      "quan-tan-binh",
      "quan-7",
      "quan-phu-nhuan",
    ],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 4,
    name: "Bún Bò Huế",
    slug: "bun-bo-hue",
    description: "Món bún bò cay thơm với nước dùng đặc trưng, thịt bò, giò heo và các loại rau thơm",
    category: "Món Ăn",
    districts: ["quan-1", "quan-5", "quan-10", "quan-phu-nhuan", "quan-binh-thanh", "quan-go-vap"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 5,
    name: "Hủ Tiếu Nam Vang",
    slug: "hu-tieu-nam-vang",
    description: "Món hủ tiếu với nước dùng trong veo, thịt, tôm, gan và các loại rau",
    category: "Món Ăn",
    districts: ["quan-5", "quan-8", "quan-11", "quan-binh-thanh", "quan-10", "quan-1"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 6,
    name: "Bún Thịt Nướng",
    slug: "bun-thit-nuong",
    description: "Bún với thịt heo nướng, chả giò, rau sống và nước mắm chua ngọt",
    category: "Món Ăn",
    districts: ["quan-1", "quan-3", "quan-10", "quan-go-vap", "quan-binh-thanh", "quan-phu-nhuan"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 10,
    name: "Bánh Xèo",
    slug: "banh-xeo",
    description: "Bánh xèo giòn với nhân tôm, thịt, giá đỗ, ăn kèm với rau sống và nước mắm chua ngọt",
    category: "Món Ăn",
    districts: ["quan-1", "quan-3", "quan-7", "quan-binh-thanh", "quan-tan-binh", "quan-go-vap"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 20,
    name: "Bún Riêu",
    slug: "bun-rieu",
    description: "Bún với nước dùng cua, đậu hũ, chả, huyết và rau sống",
    category: "Món Ăn",
    districts: ["quan-1", "quan-3", "quan-5", "quan-10", "quan-binh-thanh", "quan-go-vap"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 21,
    name: "Bún Mắm",
    slug: "bun-mam",
    description: "Bún với nước dùng mắm đặc trưng, thịt, hải sản và rau sống",
    category: "Món Ăn",
    districts: ["quan-4", "quan-5", "quan-8", "quan-7"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 22,
    name: "Cháo Lòng",
    slug: "chao-long",
    description: "Cháo với lòng heo, dồi, huyết và rau thơm",
    category: "Món Ăn",
    districts: ["quan-5", "quan-10", "quan-11", "quan-8", "quan-binh-thanh"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 23,
    name: "Hủ Tiếu Mỹ Tho",
    slug: "hu-tieu-my-tho",
    description: "Hủ tiếu với nước dùng trong, thịt, tôm, gan và hành",
    category: "Món Ăn",
    districts: ["quan-5", "quan-8", "quan-10", "quan-11"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 24,
    name: "Cơm Chiên Dương Châu",
    slug: "com-chien-duong-chau",
    description: "Cơm chiên với thịt, trứng, đậu Hà Lan và các loại rau củ",
    category: "Món Ăn",
    districts: ["quan-5", "quan-10", "quan-11", "quan-binh-thanh", "quan-phu-nhuan"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 25,
    name: "Mì Vịt Tiềm",
    slug: "mi-vit-tiem",
    description: "Mì với vịt tiềm thuốc bắc, nấm và rau thơm",
    category: "Món Ăn",
    districts: ["quan-5", "quan-10", "quan-11", "quan-8"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 26,
    name: "Lẩu Thái",
    slug: "lau-thai",
    description: "Lẩu chua cay kiểu Thái với hải sản, thịt và rau",
    category: "Món Ăn",
    districts: ["quan-1", "quan-3", "quan-5", "quan-10", "quan-7", "quan-binh-thanh"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 27,
    name: "Lẩu Cá Kèo",
    slug: "lau-ca-keo",
    description: "Lẩu với cá kèo, rau muống và các loại rau khác",
    category: "Món Ăn",
    districts: ["quan-4", "quan-7", "quan-8"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 28,
    name: "Cơm Gà Xối Mỡ",
    slug: "com-ga-xoi-mo",
    description: "Cơm với gà chiên giòn, dưa chua và nước mắm",
    category: "Món Ăn",
    districts: ["quan-1", "quan-3", "quan-10", "quan-binh-thanh", "quan-go-vap", "quan-tan-binh"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 29,
    name: "Bò Kho",
    slug: "bo-kho",
    description: "Thịt bò hầm với cà rốt, khoai tây và các loại gia vị, ăn với bánh mì hoặc hủ tiếu",
    category: "Món Ăn",
    districts: ["quan-1", "quan-3", "quan-5", "quan-10", "quan-binh-thanh", "quan-phu-nhuan"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },

  // Cà Phê
  {
    id: 7,
    name: "Cà Phê Sữa Đá",
    slug: "ca-phe-sua-da",
    description: "Cà phê đen đậm đặc pha với sữa đặc và đá, thức uống đặc trưng của Sài Gòn",
    category: "Cà Phê",
    districts: [
      "quan-1",
      "quan-3",
      "quan-binh-thanh",
      "quan-phu-nhuan",
      "thanh-pho-thu-duc",
      "quan-7",
      "quan-10",
      "quan-go-vap",
    ],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 11,
    name: "Cà Phê Trứng",
    slug: "ca-phe-trung",
    description: "Cà phê đặc biệt với lớp kem trứng béo ngậy phía trên",
    category: "Cà Phê",
    districts: ["quan-1", "quan-3", "quan-binh-thanh", "quan-phu-nhuan", "quan-7"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 30,
    name: "Cà Phê Đen Đá",
    slug: "ca-phe-den-da",
    description: "Cà phê đen đậm đặc với đá, vị đắng đặc trưng",
    category: "Cà Phê",
    districts: [
      "quan-1",
      "quan-3",
      "quan-binh-thanh",
      "quan-phu-nhuan",
      "quan-7",
      "quan-10",
      "quan-go-vap",
      "thanh-pho-thu-duc",
    ],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 31,
    name: "Bạc Xỉu",
    slug: "bac-xiu",
    description: "Cà phê sữa với nhiều sữa hơn cà phê, vị ngọt béo",
    category: "Cà Phê",
    districts: ["quan-1", "quan-3", "quan-binh-thanh", "quan-phu-nhuan", "quan-7", "quan-10", "quan-go-vap"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 32,
    name: "Cà Phê Cốt Dừa",
    slug: "ca-phe-cot-dua",
    description: "Cà phê với kem dừa béo ngậy",
    category: "Cà Phê",
    districts: ["quan-1", "quan-3", "quan-binh-thanh", "quan-phu-nhuan", "quan-7"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },

  // Trà Sữa
  {
    id: 8,
    name: "Trà Sữa Trân Châu",
    slug: "tra-sua-tran-chau",
    description: "Trà sữa với trân châu đường đen mềm dẻo và nhiều topping khác nhau",
    category: "Trà Sữa",
    districts: [
      "quan-1",
      "quan-3",
      "quan-7",
      "quan-10",
      "quan-binh-thanh",
      "thanh-pho-thu-duc",
      "quan-phu-nhuan",
      "quan-go-vap",
    ],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 12,
    name: "Trà Sữa Matcha",
    slug: "tra-sua-matcha",
    description: "Trà sữa vị matcha Nhật Bản thơm ngon, béo ngậy",
    category: "Trà Sữa",
    districts: ["quan-1", "quan-7", "quan-binh-thanh", "thanh-pho-thu-duc", "quan-3", "quan-10", "quan-phu-nhuan"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 33,
    name: "Trà Sữa Socola",
    slug: "tra-sua-socola",
    description: "Trà sữa vị socola đậm đà",
    category: "Trà Sữa",
    districts: ["quan-1", "quan-7", "quan-binh-thanh", "thanh-pho-thu-duc", "quan-3", "quan-10", "quan-phu-nhuan"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 34,
    name: "Trà Sữa Dâu",
    slug: "tra-sua-dau",
    description: "Trà sữa vị dâu tây thơm ngọt",
    category: "Trà Sữa",
    districts: ["quan-1", "quan-7", "quan-binh-thanh", "thanh-pho-thu-duc", "quan-3", "quan-10", "quan-phu-nhuan"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 35,
    name: "Trà Sữa Khoai Môn",
    slug: "tra-sua-khoai-mon",
    description: "Trà sữa vị khoai môn béo ngậy",
    category: "Trà Sữa",
    districts: ["quan-1", "quan-7", "quan-binh-thanh", "thanh-pho-thu-duc", "quan-3"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },

  // Ăn Vặt
  {
    id: 9,
    name: "Bánh Tráng Trộn",
    slug: "banh-trang-tron",
    description: "Món ăn vặt với bánh tráng cắt sợi trộn với trứng cút, khô bò, rau răm và các loại sốt",
    category: "Ăn Vặt",
    districts: ["quan-1", "quan-3", "quan-10", "quan-phu-nhuan", "quan-go-vap", "quan-binh-thanh", "quan-tan-binh"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 36,
    name: "Bánh Tráng Nướng",
    slug: "banh-trang-nuong",
    description: "Bánh tráng nướng với trứng, hành, bơ và các loại topping",
    category: "Ăn Vặt",
    districts: ["quan-1", "quan-3", "quan-10", "quan-phu-nhuan", "quan-go-vap", "quan-binh-thanh"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 37,
    name: "Ốc Các Loại",
    slug: "oc-cac-loai",
    description: "Các loại ốc hấp, xào với sả ớt, me, muối ớt...",
    category: "Ăn Vặt",
    districts: ["quan-4", "quan-10", "quan-binh-thanh", "quan-phu-nhuan", "quan-go-vap"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 38,
    name: "Sữa Chua Trân Châu",
    slug: "sua-chua-tran-chau",
    description: "Sữa chua với trân châu đường đen và các loại topping",
    category: "Ăn Vặt",
    districts: ["quan-1", "quan-3", "quan-10", "quan-phu-nhuan", "quan-go-vap", "quan-binh-thanh", "quan-7"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 39,
    name: "Chè Thái",
    slug: "che-thai",
    description: "Chè với sữa, trái cây, thạch và đậu",
    category: "Ăn Vặt",
    districts: ["quan-5", "quan-10", "quan-11", "quan-binh-thanh", "quan-phu-nhuan", "quan-3", "quan-1"],
    imageUrl: "/placeholder.svg?height=400&width=400",
  },
]

export const restaurants: Restaurant[] = [
  // Quận 1
  // Cơm Tấm - Quận 1
  {
    id: 1,
    name: "Cơm Tấm Bụi Sài Gòn",
    address: "100 Lê Thánh Tôn, Phường Bến Nghé, Quận 1",
    district: "quan-1",
    foods: ["com-tam"],
    phone: "028 3823 1234",
    hours: "6:00 - 22:00",
    priceRange: "45.000đ - 75.000đ",
    rating: 4.5,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 2,
    name: "Cơm Tấm Thuận Kiều",
    address: "25 Nguyễn Trãi, Phường Bến Thành, Quận 1",
    district: "quan-1",
    foods: ["com-tam"],
    phone: "028 3925 6789",
    hours: "6:30 - 21:00",
    priceRange: "40.000đ - 65.000đ",
    rating: 4.3,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },

  // Phở - Quận 1
  {
    id: 3,
    name: "Phở Lệ",
    address: "413-415 Nguyễn Trãi, Phường Nguyễn Cư Trinh, Quận 1",
    district: "quan-1",
    foods: ["pho"],
    phone: "028 3925 0505",
    hours: "6:00 - 22:00",
    priceRange: "65.000đ - 95.000đ",
    rating: 4.7,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 40,
    name: "Phở Phú Vương",
    address: "120 Lý Tự Trọng, Phường Bến Thành, Quận 1",
    district: "quan-1",
    foods: ["pho"],
    phone: "028 3822 2533",
    hours: "6:00 - 22:00",
    priceRange: "60.000đ - 90.000đ",
    rating: 4.5,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },

  // Bánh Mì - Quận 1
  {
    id: 5,
    name: "Bánh Mì Huỳnh Hoa",
    address: "26 Lê Thị Riêng, Phường Bến Thành, Quận 1",
    district: "quan-1",
    foods: ["banh-mi"],
    phone: "028 3820 1220",
    hours: "14:00 - 22:00",
    priceRange: "35.000đ - 55.000đ",
    rating: 4.8,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 41,
    name: "Bánh Mì Phượng Hà Nội",
    address: "57 Nguyễn Du, Phường Bến Nghé, Quận 1",
    district: "quan-1",
    foods: ["banh-mi"],
    phone: "090 123 4567",
    hours: "6:00 - 20:00",
    priceRange: "25.000đ - 45.000đ",
    rating: 4.4,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },

  // Bún Bò Huế - Quận 1
  {
    id: 7,
    name: "Bún Bò Huế Đông Ba",
    address: "110A Nguyễn Du, Phường Bến Thành, Quận 1",
    district: "quan-1",
    foods: ["bun-bo-hue"],
    phone: "028 3827 7099",
    hours: "6:30 - 21:30",
    priceRange: "55.000đ - 85.000đ",
    rating: 4.5,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 42,
    name: "Bún Bò Huế 31",
    address: "31 Mạc Thị Bưởi, Phường Bến Nghé, Quận 1",
    district: "quan-1",
    foods: ["bun-bo-hue"],
    phone: "028 3823 1234",
    hours: "6:00 - 22:00",
    priceRange: "60.000đ - 90.000đ",
    rating: 4.6,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },

  // Hủ Tiếu Nam Vang - Quận 1
  {
    id: 43,
    name: "Hủ Tiếu Nam Vang Nhân Nghĩa",
    address: "144 Cống Quỳnh, Phường Phạm Ngũ Lão, Quận 1",
    district: "quan-1",
    foods: ["hu-tieu-nam-vang"],
    phone: "028 3836 7943",
    hours: "6:00 - 22:00",
    priceRange: "45.000đ - 70.000đ",
    rating: 4.5,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },

  // Bún Thịt Nướng - Quận 1
  {
    id: 9,
    name: "Bún Thịt Nướng Chị Tuyền",
    address: "195 Cô Giang, Phường Cô Giang, Quận 1",
    district: "quan-1",
    foods: ["bun-thit-nuong"],
    phone: "090 815 9735",
    hours: "10:00 - 20:00",
    priceRange: "40.000đ - 60.000đ",
    rating: 4.4,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 44,
    name: "Bún Thịt Nướng Kiều Bảo",
    address: "140 Nguyễn Trãi, Phường Bến Thành, Quận 1",
    district: "quan-1",
    foods: ["bun-thit-nuong"],
    phone: "028 3925 0123",
    hours: "7:00 - 21:00",
    priceRange: "45.000đ - 65.000đ",
    rating: 4.3,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },

  // Cà Phê Sữa Đá - Quận 1
  {
    id: 10,
    name: "Cộng Cà Phê",
    address: "26 Lý Tự Trọng, Phường Bến Nghé, Quận 1",
    district: "quan-1",
    foods: ["ca-phe-sua-da", "ca-phe-trung"],
    phone: "028 3821 0066",
    hours: "7:00 - 23:00",
    priceRange: "35.000đ - 65.000đ",
    rating: 4.3,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 11,
    name: "The Coffee House",
    address: "92 Nguyễn Văn Cừ, Phường Nguyễn Cư Trinh, Quận 1",
    district: "quan-1",
    foods: ["ca-phe-sua-da", "ca-phe-den-da", "bac-xiu"],
    phone: "1800 6936",
    hours: "7:00 - 22:00",
    priceRange: "30.000đ - 60.000đ",
    rating: 4.2,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 45,
    name: "Trung Nguyên Legend",
    address: "80 Đồng Khởi, Phường Bến Nghé, Quận 1",
    district: "quan-1",
    foods: ["ca-phe-sua-da", "ca-phe-den-da", "bac-xiu"],
    phone: "028 3829 6283",
    hours: "7:00 - 22:00",
    priceRange: "40.000đ - 75.000đ",
    rating: 4.4,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },

  // Trà Sữa - Quận 1
  {
    id: 12,
    name: "Gong Cha",
    address: "68 Nguyễn Huệ, Phường Bến Nghé, Quận 1",
    district: "quan-1",
    foods: ["tra-sua-tran-chau", "tra-sua-matcha", "tra-sua-socola", "tra-sua-dau"],
    phone: "028 3821 9012",
    hours: "9:00 - 22:00",
    priceRange: "45.000đ - 75.000đ",
    rating: 4.4,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 13,
    name: "KOI Thé",
    address: "42 Nguyễn Huệ, Phường Bến Nghé, Quận 1",
    district: "quan-1",
    foods: ["tra-sua-tran-chau", "tra-sua-matcha", "tra-sua-socola", "tra-sua-dau", "tra-sua-khoai-mon"],
    phone: "028 3821 7651",
    hours: "10:00 - 22:00",
    priceRange: "50.000đ - 80.000đ",
    rating: 4.5,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 46,
    name: "Tiger Sugar",
    address: "136 Nguyễn Trãi, Phường Bến Thành, Quận 1",
    district: "quan-1",
    foods: ["tra-sua-tran-chau", "tra-sua-matcha", "tra-sua-socola"],
    phone: "028 3926 2468",
    hours: "10:00 - 22:00",
    priceRange: "45.000đ - 75.000đ",
    rating: 4.3,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },

  // Bánh Tráng Trộn - Quận 1
  {
    id: 14,
    name: "Bánh Tráng Trộn Chú Viên",
    address: "37 Nguyễn Trãi, Phường Bến Thành, Quận 1",
    district: "quan-1",
    foods: ["banh-trang-tron", "banh-trang-nuong"],
    phone: "090 123 4567",
    hours: "14:00 - 22:00",
    priceRange: "20.000đ - 35.000đ",
    rating: 4.3,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 47,
    name: "Bánh Tráng Trộn Cô Ba",
    address: "76 Lê Anh Xuân, Phường Bến Thành, Quận 1",
    district: "quan-1",
    foods: ["banh-trang-tron", "banh-trang-nuong"],
    phone: "090 987 6543",
    hours: "14:00 - 22:00",
    priceRange: "20.000đ - 35.000đ",
    rating: 4.2,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },

  // Bánh Xèo - Quận 1
  {
    id: 15,
    name: "Bánh Xèo 46A",
    address: "46A Đinh Công Tráng, Phường Tân Định, Quận 1",
    district: "quan-1",
    foods: ["banh-xeo"],
    phone: "028 3824 1110",
    hours: "10:00 - 21:00",
    priceRange: "65.000đ - 120.000đ",
    rating: 4.6,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 48,
    name: "Bánh Xèo Miền Trung",
    address: "22 Nguyễn Thị Nghĩa, Phường Bến Thành, Quận 1",
    district: "quan-1",
    foods: ["banh-xeo"],
    phone: "028 3925 1234",
    hours: "10:00 - 21:00",
    priceRange: "60.000đ - 100.000đ",
    rating: 4.4,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },

  // Bún Riêu - Quận 1
  {
    id: 49,
    name: "Bún Riêu Cua Nguyễn Du",
    address: "18 Nguyễn Du, Phường Bến Nghé, Quận 1",
    district: "quan-1",
    foods: ["bun-rieu"],
    phone: "028 3829 1234",
    hours: "6:00 - 13:00",
    priceRange: "45.000đ - 65.000đ",
    rating: 4.5,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },

  // Bò Kho - Quận 1
  {
    id: 50,
    name: "Bò Kho Út Nhung",
    address: "109 Nguyễn Thái Học, Phường Cầu Ông Lãnh, Quận 1",
    district: "quan-1",
    foods: ["bo-kho"],
    phone: "028 3837 2723",
    hours: "6:00 - 11:00, 16:00 - 21:00",
    priceRange: "50.000đ - 70.000đ",
    rating: 4.6,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },

  // Quận 3
  // Phở - Quận 3
  {
    id: 4,
    name: "Phở Hòa",
    address: "260C Pasteur, Phường 8, Quận 3",
    district: "quan-3",
    foods: ["pho"],
    phone: "028 3829 7943",
    hours: "6:30 - 22:30",
    priceRange: "60.000đ - 90.000đ",
    rating: 4.6,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 51,
    name: "Phở Phượng",
    address: "25 Hoàng Sa, Phường Đa Kao, Quận 3",
    district: "quan-3",
    foods: ["pho"],
    phone: "028 3829 2756",
    hours: "6:00 - 22:00",
    priceRange: "55.000đ - 85.000đ",
    rating: 4.4,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },

  // Bánh Mì - Quận 3
  {
    id: 6,
    name: "Bánh Mì Hòa Mã",
    address: "53 Cao Thắng, Phường 3, Quận 3",
    district: "quan-3",
    foods: ["banh-mi"],
    phone: "028 3834 5665",
    hours: "6:00 - 11:00",
    priceRange: "25.000đ - 40.000đ",
    rating: 4.4,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },

  // Cà Phê - Quận 3
  {
    id: 52,
    name: "Là Việt Coffee",
    address: "191 Hai Bà Trưng, Phường 6, Quận 3",
    district: "quan-3",
    foods: ["ca-phe-sua-da", "ca-phe-den-da", "ca-phe-trung"],
    phone: "028 3820 4779",
    hours: "7:00 - 22:00",
    priceRange: "40.000đ - 70.000đ",
    rating: 4.5,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 53,
    name: "Maison Marou Café",
    address: "167-169 Calmette, Phường Nguyễn Thái Bình, Quận 3",
    district: "quan-3",
    foods: ["ca-phe-sua-da", "ca-phe-den-da"],
    phone: "028 3827 0131",
    hours: "9:00 - 22:00",
    priceRange: "50.000đ - 90.000đ",
    rating: 4.7,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },

  // Trà Sữa - Quận 3
  {
    id: 54,
    name: "Phúc Long Coffee & Tea",
    address: "42 Trần Cao Vân, Phường 6, Quận 3",
    district: "quan-3",
    foods: ["tra-sua-tran-chau", "ca-phe-sua-da", "ca-phe-den-da"],
    phone: "028 3526 2737",
    hours: "7:00 - 22:00",
    priceRange: "35.000đ - 65.000đ",
    rating: 4.3,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },

  // Quận Bình Thạnh
  {
    id: 16,
    name: "Phúc Long Coffee & Tea",
    address: "42 Phan Xích Long, Phường 3, Quận Bình Thạnh",
    district: "quan-binh-thanh",
    foods: ["ca-phe-sua-da", "tra-sua-tran-chau"],
    phone: "028 3510 6263",
    hours: "7:00 - 22:30",
    priceRange: "35.000đ - 70.000đ",
    rating: 4.3,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 17,
    name: "Cơm Tấm Cali",
    address: "151 Phan Đăng Lưu, Phường 7, Quận Bình Thạnh",
    district: "quan-binh-thanh",
    foods: ["com-tam"],
    phone: "028 3510 8866",
    hours: "6:00 - 22:00",
    priceRange: "50.000đ - 80.000đ",
    rating: 4.4,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 55,
    name: "Phở Lệ",
    address: "303-305 Võ Văn Tần, Phường 5, Quận Bình Thạnh",
    district: "quan-binh-thanh",
    foods: ["pho"],
    phone: "028 3820 2230",
    hours: "6:00 - 22:00",
    priceRange: "65.000đ - 95.000đ",
    rating: 4.6,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 56,
    name: "Bún Thịt Nướng Kiều Bảo",
    address: "283 Phan Xích Long, Phường 2, Quận Bình Thạnh",
    district: "quan-binh-thanh",
    foods: ["bun-thit-nuong"],
    phone: "028 3510 1234",
    hours: "7:00 - 21:00",
    priceRange: "45.000đ - 65.000đ",
    rating: 4.3,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },

  // Thành phố Thủ Đức
  {
    id: 18,
    name: "Trà Sữa Bobapop",
    address: "Vincom Thủ Đức, 216 Võ Văn Ngân, Phường Bình Thọ, TP. Thủ Đức",
    district: "thanh-pho-thu-duc",
    foods: ["tra-sua-tran-chau", "tra-sua-matcha"],
    phone: "028 3720 1234",
    hours: "9:00 - 22:00",
    priceRange: "40.000đ - 65.000đ",
    rating: 4.2,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 19,
    name: "Highlands Coffee",
    address: "TTTM Gigamall, 240 Phạm Văn Đồng, Phường Hiệp Bình Chánh, TP. Thủ Đức",
    district: "thanh-pho-thu-duc",
    foods: ["ca-phe-sua-da"],
    phone: "1900 1755",
    hours: "7:00 - 22:00",
    priceRange: "35.000đ - 65.000đ",
    rating: 4.1,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 57,
    name: "Phúc Long Coffee & Tea",
    address: "TTTM Vincom Thủ Đức, 216 Võ Văn Ngân, Phường Bình Thọ, TP. Thủ Đức",
    district: "thanh-pho-thu-duc",
    foods: ["ca-phe-sua-da", "tra-sua-tran-chau"],
    phone: "028 3720 5678",
    hours: "8:00 - 22:00",
    priceRange: "35.000đ - 70.000đ",
    rating: 4.3,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },

  // Quận 7
  {
    id: 58,
    name: "Cơm Tấm Kiều Giang",
    address: "101 Nguyễn Thị Thập, Phường Tân Phú, Quận 7",
    district: "quan-7",
    foods: ["com-tam"],
    phone: "028 3771 1234",
    hours: "6:00 - 22:00",
    priceRange: "45.000đ - 75.000đ",
    rating: 4.4,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 59,
    name: "Phở 24",
    address: "1057 Huỳnh Tấn Phát, Phường Phú Thuận, Quận 7",
    district: "quan-7",
    foods: ["pho"],
    phone: "028 3773 2424",
    hours: "6:00 - 22:00",
    priceRange: "55.000đ - 85.000đ",
    rating: 4.2,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 60,
    name: "The Coffee Bean & Tea Leaf",
    address: "Crescent Mall, 101 Tôn Dật Tiên, Phường Tân Phú, Quận 7",
    district: "quan-7",
    foods: ["ca-phe-sua-da", "ca-phe-den-da"],
    phone: "028 5413 7191",
    hours: "7:00 - 22:00",
    priceRange: "50.000đ - 90.000đ",
    rating: 4.3,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },

  // Quận 10
  {
    id: 61,
    name: "Cơm Tấm Ngọc Sương",
    address: "237 Cao Thắng, Phường 12, Quận 10",
    district: "quan-10",
    foods: ["com-tam"],
    phone: "028 3868 1234",
    hours: "6:00 - 22:00",
    priceRange: "40.000đ - 70.000đ",
    rating: 4.3,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 62,
    name: "Bún Bò Huế 3 Thi",
    address: "283 Sư Vạn Hạnh, Phường 10, Quận 10",
    district: "quan-10",
    foods: ["bun-bo-hue"],
    phone: "028 3863 5678",
    hours: "6:00 - 22:00",
    priceRange: "50.000đ - 80.000đ",
    rating: 4.5,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 63,
    name: "Trà Sữa Gong Cha",
    address: "Vạn Hạnh Mall, 11 Sư Vạn Hạnh, Phường 12, Quận 10",
    district: "quan-10",
    foods: ["tra-sua-tran-chau", "tra-sua-matcha", "tra-sua-socola"],
    phone: "028 3868 9012",
    hours: "9:00 - 22:00",
    priceRange: "45.000đ - 75.000đ",
    rating: 4.4,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },

  // Quận Gò Vấp
  {
    id: 64,
    name: "Cơm Tấm Thuận Kiều",
    address: "283 Quang Trung, Phường 10, Quận Gò Vấp",
    district: "quan-go-vap",
    foods: ["com-tam"],
    phone: "028 3894 1234",
    hours: "6:00 - 22:00",
    priceRange: "40.000đ - 65.000đ",
    rating: 4.2,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 65,
    name: "Phở Hà Nội",
    address: "190 Nguyễn Oanh, Phường 17, Quận Gò Vấp",
    district: "quan-go-vap",
    foods: ["pho"],
    phone: "028 3894 5678",
    hours: "6:00 - 22:00",
    priceRange: "50.000đ - 80.000đ",
    rating: 4.3,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 66,
    name: "Trà Sữa Toco Toco",
    address: "242 Nguyễn Văn Nghi, Phường 7, Quận Gò Vấp",
    district: "quan-go-vap",
    foods: ["tra-sua-tran-chau", "tra-sua-matcha"],
    phone: "028 3894 9012",
    hours: "9:00 - 22:00",
    priceRange: "35.000đ - 65.000đ",
    rating: 4.1,
    imageUrl: "/placeholder.svg?height=300&width=500",
  },
]

export function getAllDistricts(): District[] {
  return districts
}

export function getDistrictBySlug(slug: string): District | undefined {
  return districts.find((district) => district.slug === slug)
}

export function getAllFoods(): Food[] {
  return foods
}

export function getFoodBySlug(slug: string): Food | undefined {
  return foods.find((food) => food.slug === slug)
}

export function getFoodsByDistrict(districtSlug: string): Food[] {
  return foods.filter((food) => food.districts.includes(districtSlug))
}

export function getRestaurantsByDistrictAndFood(districtSlug: string, foodSlug: string): Restaurant[] {
  return restaurants.filter((restaurant) => restaurant.district === districtSlug && restaurant.foods.includes(foodSlug))
}
